### ISSUE TITLE
Fix unit tests

### ISSUE THREAD

**Issue by eile** [VMML/vmmlib#73]
After fixing the test macros in #72, we finally see that the tests were useless since most of them fail:
```
====== TEST OVERVIEW ====== 
tests:        450
warnings:     7
failed tests: 335
=========================== 
```

Btw, every time one writes code like this, a little stop bit dies. Why not use something simple like Lunchbox does or something tested like boost::unit_test?

**Comment by rballester** [comment]
vmmlib has now adopted boost::unit_test for current and future tests.
