### ISSUE TITLE
Reserved identifiers in include guards

### ISSUE THREAD

**Issue by juanchopanza** [VMML/vmmlib#88]
I have seen plenty of include guards using double underscores. These are C++ reserved identifiers and using them is technically undefined behaviour. I realise the chances of a name clash with an implementation identifier are slim, but it is still a good idea to remove UB and in this case it seems quite easy to do.

**Comment by rballester** [comment]
You are absolutely right; this will be fixed.

**Comment by rballester** [comment]
This has been already fixed in the "release_candidate" branch. It will soon be merged to the main branch; I close the issue.
