### ISSUE TITLE
can we make the length of dimension as variable

### ISSUE THREAD

**Issue by wjian117** [VMML/vmmlib#98]
can we make the length of dimension as variable？such as "vmml::tensor3< 500, 500, 100, float > data "
can we make the value 500,500,100 as variable,because may be the dimensions of the data are not fixed.

**Comment by rballester** [comment]
Hi wjian117, this is not planned in vmmlib. You may want to check [vmmlib-tensor](https://github.com/rballester/vmmlib-tensor), which supports dynamic tensor sizes.
