### ISSUE TITLE
How to compile and run a vmmlib test program?

### ISSUE THREAD

**Issue by rohitmulay** [VMML/vmmlib#99]
I have sucessfully installed vmmlib 1.7 using the following steps: 
```
mkdir vmmlib/build
cd vmmlib/build
cmake ..
make
```
Now, I'm trying to run a program in the test folder "t3_hosvd_test.cpp" , but I'm not able to run it. 
I tried to run the Makefile but got the following error: 

> svd_test.cpp:13:0:
> ../include/vmmlib/vmmlib.hpp:33:30: fatal error: vmmlib/version.hpp: No such file or directory
> compilation terminated.
> <builtin>: recipe for target 'svd_test.o' failed
> make: *** [svd_test.o] Error 1

I also tried to run by giving the following command in the terminal: 
`g++  t3_hosvd_test.cpp  -lapack -lvmmlib
`
but got an error: 

> t3_hosvd_test.cpp:2:31: fatal error: vmmlib/t3_hosvd.hpp: No such file or directory
> compilation terminated.
> 

**Can someone help me compile and run this program on Ubuntu 16.04?** 

Thank you in advance!

**Comment by rballester** [comment]
Hi Rohit, tensor functionality is no longer supported in this library. You can check out [vmmlib-tensor](https://github.com/rballester/vmmlib-tensor/) for a version supporting 3D tensors and tensor decomposition.
